### 회원가입===ok
POST http://localhost:4000/api/accounts/signup
Content-Type: application/json

{
  "email":"tjdngur14@naver.com",
  "password":"asd123",
  "confirmpassword":"asd123",
  "nickname":"asq1"
}

### 로그인====ok
POST http://localhost:4000/api/accounts/login
Content-Type: application/json

{
  "email":"tjdngur14@naver.com",
  "password":"asd123"
}

### MBTI===ok
POST http://localhost:3000/api/accounts/mbti
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsIm5pY2tuYW1lIjoiYXNxMSIsIm1idGkiOm51bGwsImlhdCI6MTY2MjIwMjk5MSwiZXhwIjoxNjYyMzc1NzkxfQ.X1iqyb85KmWSGti5Pw-ZHo5HWRwHBrXkImQ2DdDKoMo

{
  "mbti":"estj"
}


# ========================================================

### 팔로우 추가 삭제===ok
# userId는 팔로우 추가 삭제 대상
PUT  http://localhost:3000/api/followLists/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsIm5pY2tuYW1lIjoiYXNxMSIsIm1idGkiOm51bGwsImlhdCI6MTY2MjIwMjk5MSwiZXhwIjoxNjYyMzc1NzkxfQ.X1iqyb85KmWSGti5Pw-ZHo5HWRwHBrXkImQ2DdDKoMo



### 팔로우 조회====ok
# 토큰 담겨있는 userId 기준으로 
GET  http://localhost:3000/api/followLists/1
Content-Type: application/json


# ========================================================

### TODO 제안 하기 (TODO 작성)====ok
POST http://localhost:4000/api/mytodos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsIm5pY2tuYW1lIjoiYXNxMSIsIm1idGkiOm51bGwsImlhdCI6MTY2MjIwMjk5MSwiZXhwIjoxNjYyMzc1NzkxfQ.X1iqyb85KmWSGti5Pw-ZHo5HWRwHBrXkImQ2DdDKoMo

{
  "todo":"투두작성"
}


### TODO 삭제 ==ok
DELETE http://localhost:4000/api/mytodos/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsIm5pY2tuYW1lIjoiYXNxMSIsIm1idGkiOm51bGwsImlhdCI6MTY2MjIwMjk5MSwiZXhwIjoxNjYyMzc1NzkxfQ.X1iqyb85KmWSGti5Pw-ZHo5HWRwHBrXkImQ2DdDKoMo

{
  "date":"22-09-03"
}

### TODO mytodo에 담기 ===ok
POST  http://localhost:4000/api/mytodos/5/challenged
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsIm5pY2tuYW1lIjoiYXNxMSIsIm1idGkiOm51bGwsImlhdCI6MTY2MjIwMjk5MSwiZXhwIjoxNjYyMzc1NzkxfQ.X1iqyb85KmWSGti5Pw-ZHo5HWRwHBrXkImQ2DdDKoMo


### TODO mytodo 담은거 제거 
DELETE  http://localhost:4000/api/mytodos/5/challenged
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsIm5pY2tuYW1lIjoiYXNxMSIsIm1idGkiOm51bGwsImlhdCI6MTY2MjIwMjk5MSwiZXhwIjoxNjYyMzc1NzkxfQ.X1iqyb85KmWSGti5Pw-ZHo5HWRwHBrXkImQ2DdDKoMo

{
  "date":"22-09-03"
}

### TODO mytodo 도전 진행완료 or 진행취소 
PUT  http://localhost:4000/api/mytodos/1/challenged
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5pY2tuYW1lIjoiYXNxMSIsIm1idGkiOm51bGwsImlhdCI6MTY2MjE4OTA4OCwiZXhwIjoxNjYyMzYxODg4fQ.JE7Uw1OsUTvBU4F76880pyd_q-RoWYM19yXZVBxmlbg

{
  "date":"22-09-03"
}

# ========================================================
