### 회원가입
POST http://localhost:4000/api/accounts/signup
Content-Type: application/json

{
  "email":"tjdngur11@naver.com",
  "password":"asd123",
  "confirmpassword":"asd123",
  "nickname":"asq1"
}

### 로그인
POST http://localhost:4000/api/accounts
Content-Type: application/json

{
  "email":"tjdngur3@naver.com",
  "password":"asd123"
}

### MBTI
POST http://localhost:3000/api/accounts/mbti
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsIm5pY2tuYW1lIjoiYXNxMSIsIm1idGkiOm51bGwsImlhdCI6MTY2MTk1MDM4NiwiZXhwIjoxNjYyMTIzMTg2fQ.eefv54rM8SaAD91MYQRp7pyOkmPPeAykx07vuv5IkrM

{
  "mbti":"estj"
}


# ========================================================

### 팔로우 추가 삭제
# userId는 팔로우 추가 삭제 대상
PUT  http://localhost:3000/api/followLists/5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsIm5pY2tuYW1lIjoiYXNxMSIsIm1idGkiOm51bGwsImlhdCI6MTY2MTk2MTA3MiwiZXhwIjoxNjYyMTMzODcyfQ.VJbcNpjiBSeaBuM45f0EE_aV8rhs5Af-xFUIL0pLgCQ



### 팔로우 조회
# 토큰 담겨있는 userId 기준으로 
GET  http://localhost:3000/api/followLists/1
Content-Type: application/json


# ========================================================

### TODO 제안 하기 (TODO 작성)====ok
POST http://localhost:4000/api/mytodos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5pY2tuYW1lIjoiYXNxMSIsIm1idGkiOm51bGwsImlhdCI6MTY2MjE4OTA4OCwiZXhwIjoxNjYyMzYxODg4fQ.JE7Uw1OsUTvBU4F76880pyd_q-RoWYM19yXZVBxmlbg

{
  "todo":"투두작성"
}


### TODO 삭제 ==ok
DELETE http://localhost:4000/api/mytodos/5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5pY2tuYW1lIjoiYXNxMSIsIm1idGkiOm51bGwsImlhdCI6MTY2MjE4OTA4OCwiZXhwIjoxNjYyMzYxODg4fQ.JE7Uw1OsUTvBU4F76880pyd_q-RoWYM19yXZVBxmlbg

{
  "date":"22-09-03"
}

### TODO mytodo에 담기 ===ok
POST  http://localhost:4000/api/mytodos/5/challenged
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5pY2tuYW1lIjoiYXNxMSIsIm1idGkiOm51bGwsImlhdCI6MTY2MjE4OTA4OCwiZXhwIjoxNjYyMzYxODg4fQ.JE7Uw1OsUTvBU4F76880pyd_q-RoWYM19yXZVBxmlbg


### TODO mytodo 담은거 제거 ===ok
DELETE  http://localhost:4000/api/mytodos/5/challenged
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5pY2tuYW1lIjoiYXNxMSIsIm1idGkiOm51bGwsImlhdCI6MTY2MjE4OTA4OCwiZXhwIjoxNjYyMzYxODg4fQ.JE7Uw1OsUTvBU4F76880pyd_q-RoWYM19yXZVBxmlbg

{
  "date":"22-09-03"
}

### TODO mytodo 도전 진행완료 or 진행취소 ===ok
PUT  http://localhost:4000/api/mytodos/1/challenged
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5pY2tuYW1lIjoiYXNxMSIsIm1idGkiOm51bGwsImlhdCI6MTY2MjE4OTA4OCwiZXhwIjoxNjYyMzYxODg4fQ.JE7Uw1OsUTvBU4F76880pyd_q-RoWYM19yXZVBxmlbg

{
  "date":"22-09-03"
}

# ========================================================

### 장바구니 조회
GET http://localhost:3000/cart
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJxd2UxMjMiLCJuaWNrTmFtZSI6Im5pY2tuYW0iLCJlbWFpbCI6ImVtYWlsQG5hdmVyLmNvbSIsImFkZHJlc3MiOiLtlZzqta0g7ISc7Jq4IiwiaWF0IjoxNjYxMzI3NTcxLCJleHAiOjE2NjE1MDAzNzF9.qR2n1xgzbUUWDmE-LEEAJ9sEVyeNSr2i3JWJotmVHZA


### 장바구니 등록, 갯수 수정
POST http://localhost:3000/cart/5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJxd2UxMjMiLCJuaWNrTmFtZSI6Im5pY2tuYW0iLCJlbWFpbCI6ImVtYWlsQG5hdmVyLmNvbSIsImFkZHJlc3MiOiLtlZzqta0g7ISc7Jq4IiwiaWF0IjoxNjYxMzI3NTcxLCJleHAiOjE2NjE1MDAzNzF9.qR2n1xgzbUUWDmE-LEEAJ9sEVyeNSr2i3JWJotmVHZA


{
    "quantity": 1
}


### 장바구니 삭제
DELETE http://localhost:3000/cart/5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJxd2UxMjMiLCJuaWNrTmFtZSI6Im5pY2tuYW0iLCJlbWFpbCI6ImVtYWlsQG5hdmVyLmNvbSIsImFkZHJlc3MiOiLtlZzqta0g7ISc7Jq4IiwiaWF0IjoxNjYxMzI3NTcxLCJleHAiOjE2NjE1MDAzNzF9.qR2n1xgzbUUWDmE-LEEAJ9sEVyeNSr2i3JWJotmVHZA